name: Aliyun Signin

on:
  schedule:
   # 每天国际时间 09:30 运行一次, 中国时间 01:30
    - cron: '30 18 * * *' # 对应中国时间每天凌晨1:30运行一次
    
  workflow_dispatch:
jobs:
  signin:
    name: Aliyun Signin
    runs-on: ubuntu-latest
    steps:
      - uses: ImYrS/aliyun-auto-signin@main
        with:
          REFRESH_TOKENS: ${{ secrets.REFRESH_TOKENS }}
          GP_TOKEN: ${{ secrets.GP_TOKEN}}
          PUSH_TYPES: 'pushplus'
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
  
